spring:
  mvc:
    static-path-pattern: /static/**
  #  web:
#    resources:
#      static-locations: [classpath:/static/]
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_management_system
    username: root
    password: mo
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
##  configuration: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
